### ISSUE TITLE
What package manager used by this project, yarn or npm?

### ISSUE THREAD

**Issue by nyancodeid** [masbagal/tempe#5]
Btw, thanks for make most wanted featured on `moment.js` and the good thing is that lightweight :100: 

After see source-code and i realize there is,  2 lock files appear. There is `package-lock.json` and `yarn.lock` that should one lock file appear for every project. If you mix it by using yarn or npm at the same time, you should choice one of them to make sure there is no unsynchronized lock files.

### Steps to Reproduce
When i start `yarn install` at the first time clone, it appear this message on terminal.
```
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
```

### Possible Solution
- Delete both of them (lock files)
- Delete node_modules/
- re-install using one of package manager will be used (yarn or npm)

I think `yarn` is faster one :1st_place_medal:

**Comment by ridhoassuryadi** [comment]
i see, nice catch.. i thinks there is 2 posibilities about that

* We ignore that locks either `yarn` or `npm` , let the lock depend on the contributor whether he uses yarn or npm.

* Or we choose one of them like @nyancodeid  mention it, which uses yarn as the default package manager

wdyt @masbagal  ?

**Comment by masbagal** [comment]
Nice catch @nyancodeid, thanks a lot. This is mainly because I switched laptop a lot when creating this.

Also thanks @ridhoassuryadi for the suggestion. I think lock file is needed so I don't think ignoring it is an option. I also prefer to use `yarn` as default because it felt more reliable.

I can make the adjustment, but does anyone here want to create the PR? Maybe @nyancodeid as the reporter so it will be well-credited as a contributor?

**Comment by nyancodeid** [comment]
@masbagal Sure, i appreciate it. I will create new PR for it.

**Comment by masbagal** [comment]
Merged, thanks everyone
